# Generated by Django 5.0.6 on 2024-06-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_pedidoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
