# Generated by Django 5.0.6 on 2024-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delete_pedidoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
