# Generated by Django 5.0.6 on 2024-06-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
